# test for ui

f.setTitle "Test App"
f.writeAs "choose" atX 10 atY 10 value "Choose" onClickGoto :CHOOSE
f.writeAs "ask" atX 10 atY 40 value "Ask" onClickGoto :ASK
stop

:ASK
  platform.exec "ui" withArgs "ask -prompt \qYour Name\q -value Chris -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:CHOOSE
  platform.exec "ui" withArgs "choose -prompt \qYour Name\q -items \qhello/world/from/me\q -value 2 -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:READ
  T = platform.readFromFile "test.txt"
  echo T
  stop
  
:FAIL
  f.writeAs "error" atX 0 atY 0 colour "#f00" value "Failed"
  stop
